### ISSUE TITLE
how to calculate velocity 

### ISSUE THREAD

**Issue by codegcf** [codegcf/seoulrobotics-assignment#1]
i did some research, it seems the /velocity topic has coordinates x y z (linear and angular) ; to find the anomaly component z has to have velocity > 4.5.
my question is will it be calculated mathematically with linear/angular "z" ; or am I misunderstanding? thank you

@jungsu-kwon @minhoon-dev

**Comment by jungsu-kwon** [comment]
```bash
$ rosbag info data/data.bag
path:         data/data.bag
version:      2.0
duration:     1:21s (81s)
start:        Dec 22 2021 01:29:01.30 (1640136541.30)
end:          Dec 22 2021 01:30:22.50 (1640136622.50)
size:         658.9 MB
messages:     12991
compression:  lz4 [812/812 chunks; 54.07%]
uncompressed:   1.2 GB @ 15.0 MB/s
compressed:   658.5 MB @  8.1 MB/s (54.07%)
types:        geometry_msgs/Twist     [9f195f881246fdfa2798d1d3eebca84a]
              sensor_msgs/PointCloud2 [1158d486dd51d683ce2f1be655c3c181]
topics:       /lidar_0000/os_cloud_node/points     811 msgs    : sensor_msgs/PointCloud2
              /velocity                          12180 msgs    : geometry_msgs/Twist
``` 

you can use this part!
```
/velocity                          12180 msgs    : geometry_msgs/Twist
```

**Comment by codegcf** [comment]
@jungsu-kwon 


i did get to extract the content but my question is is the 'z' component talked about the 'angular z' ? bc the linear has only 0 as far as i can see. 

like _**below**_ is what i got from '/velocity' topic.

<html>
<body>


Time | linear.x | linear.y | linear.z | angular.x | angular.y | angular.z
-- | -- | -- | -- | -- | -- | --
1.640137e+09 | 2.404513 | 0.002327 | 0.0 | 0.0 | 0.0 | 0.000902
1.640137e+09 | 2.437066 | 0.002365 | 0.0 | 0.0 | 0.0 | 0.000914
1.640137e+09 | 2.437065 | 0.002601 | 0.0 | 0.0 | 0.0 | 0.001006
1.640137e+09 | 2.437065 | 0.002601 | 0.0 | 0.0 | 0.0 | 0.001006
1.640137e+09 | 2.471787 | 0.002629 | 0.0 | 0.0 | 0.0 | 0.001020


</body>
</html>

**Comment by jungsu-kwon** [comment]
@codegcf there are only 12 data points amongst 12180 points where linear.z is over 4.5.

As you have pointed out in the above table, most of the linear.z value is 0.0.

I have manually modified data to simulate anomalies.

I advise you to check using code, not with your eyes.

To make sure, there are points with 4.5 velocity.linear.z

I have just double-checked.  

```
x: 6.282711982727051
y: 0.7376812696456909
z: 5.0
x: 11.106744766235352
y: 0.03431190177798271
z: 5.0
x: 8.298602104187012
y: 0.017595410346984863
z: 5.0
x: 2.8580241203308105
y: 0.02364695444703102
z: 5.0
x: 4.982629776000977
y: 0.01394549198448658
z: 5.0
x: 7.052933692932129
y: 0.022443104535341263
z: 5.0
x: 8.667509078979492
y: 0.030118321999907494
z: 5.0
x: 7.749561309814453
y: 0.011926145292818546
z: 5.0
x: 4.3467864990234375
y: -0.005876857787370682
z: 5.0
x: 2.2156729698181152
y: 0.018569516018033028
z: 5.0
x: 3.276909589767456
y: 0.0015799133107066154
z: 5.0
x: 0.8094580769538879
y: 0.003484169254079461
z: 5.0
```

If you still have questions let me know I will answer asap

**Comment by codegcf** [comment]
@jungsu-kwon thank YOU for clarifying i wasn't sure which exact z component it was!
